### ISSUE TITLE
What is the difference between Custom and Stargate querier?

### ISSUE THREAD

**Issue by ulbqb** [Finschia/wasmd#115]
https://github.com/Finschia/wasmd/blob/c83ad2f3e36801060759d83df133ddcbd4106139/x/wasm/keeper/query_plugins.go#L109

This function is duplicated with Stargate querier.

**Comment by ulbqb** [comment]
Generally, custom query seems to be used for pre-defined one like
https://github.com/osmosis-labs/osmosis/blob/d05e6b11a7c5c02b8b424b5d5820ee3ac4ed048b/wasmbinding/query_plugin.go#L52
https://github.com/neutron-org/neutron/blob/fee60f7aa0f8694749172b3d99c66882d5fb80f3/wasmbinding/custom_querier.go#L15

But we released it as CustomQuerierImpl and can't remove this.

**Comment by loloicci** [comment]
This is a bug that the custom query is still alive. If there is no problem to close this, we will close it.
